### PR TITLE
Fix 84

### LINKED ISSUE #84: Add tracking data in plugin: Settings, admin choice and data tracking
Describe the bug
Add the data tracking code in the plugin to ensure all the relevant details (global settings, product settings etc.) are sent back to the tracking server.

Additional context
https://docs.google.com/document/d/1T-4QcwvO1K-dZLFQwOxC_xvPjX4QFFXuSqt1bNn7lU4/edit

The tracking code needs to be implemented at v2

Tyche Javascript Constructor: https://github.com/TycheSoftwares/tyche-js-constructor
Plugin Tracking: https://github.com/TycheSoftwares/tyche-plugin-tracking
Plugin Deactivation: https://github.com/TycheSoftwares/tyche-plugin-deactivation

### PR DESCRIPTION
**Pull request by PratapDungrani**
added code to send PIF global and product level settings.

Fix #84

### CODE REVIEW

File: product-input-fields-for-woocommerce.php [hunk 1]
```diff
@@ -194,6 +194,9 @@ public function includes() {
 
 			if ( is_admin() ) {
 
+				require_once 'includes/class-pif-tracking-functions.php';
+				add_filter( 'ts_tracker_data', array( __CLASS__, 'pif_lite_ts_add_plugin_tracking_data' ), 10, 1 );
```
Comment (handelce) [inline product-input-fields-for-woocommerce.php:198]: @PratapDungrani Let's do the following:
1. Rename **class-pif-tracking-functions.php** to **class-alg-wc-pif-tracking.php**
2. Add the hook to the **class-alg-wc-pif-tracking.php** file.
3. Remove the class instantiation code from inside the class file itself and have it after the file has been loaded.

**Review by handelce — CHANGES_REQUESTED** [review]

**Review by handelce — APPROVED** [review]
