### PR TITLE
Fix 84

### LINKED ISSUE #84: Add tracking data in plugin: Settings, admin choice and data tracking
Describe the bug
Add the data tracking code in the plugin to ensure all the relevant details (global settings, product settings etc.) are sent back to the tracking server.

Additional context
https://docs.google.com/document/d/1T-4QcwvO1K-dZLFQwOxC_xvPjX4QFFXuSqt1bNn7lU4/edit

The tracking code needs to be implemented at v2

Tyche Javascript Constructor: https://github.com/TycheSoftwares/tyche-js-constructor
Plugin Tracking: https://github.com/TycheSoftwares/tyche-plugin-tracking
Plugin Deactivation: https://github.com/TycheSoftwares/tyche-plugin-deactivation

### PR DESCRIPTION
**Pull request by PratapDungrani**
Replaced usage tracking data from v1 to v2.

Fix #84

### CODE REVIEW

**Review by handelce — CHANGES_REQUESTED** [review]
**1. On activation of the plugin, there are two tracking notices** 

image

**2. The tracking notice is shown on all of the pages on the WooCommerce Settings page. This is wrong.** 

image

3. When I click on the "Allow" or "No thanks" button, the page redirects to the PIF Settings page. The page should reload back to the same page from which the buttons were clicked.

4. I did not see any code for consideration of users who already have tracking enabled in v1. With what you've done, the Tracking Notice will be displayed for them again. The ideal workflow should be that your code should update the system variables and not display the Tracking Notice for them again.

File: includes/component/plugin-tracking/class-tyche-plugin-tracking.php [hunk 1]
```diff
@@ -243,6 +243,11 @@ public function display_tracker_html_template() {
 				return;
 			}
 
+			$is_specific_page = apply_filters( $this->plugin_short_name . '_ts_tracker_display_notice', true );
```
Comment (handelce) [inline includes/component/plugin-tracking/class-tyche-plugin-tracking.php:246]: @PratapDungrani Please add this condition into the code block [here](https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/blob/2d5b3e798cfa0af64b685381f3393ac569fb3d78/includes/component/plugin-tracking/class-tyche-plugin-tracking.php#L242). This way, we can have one code block that terminates the block execution.

File: product-input-fields-for-woocommerce.php [hunk 2]
```diff
@@ -244,8 +244,10 @@ public static function ts_admin_notices_scripts() {
 		 * Add tracker completed.
 		 */
 		public static function init_tracker_completed() {
-			header( 'Location: ' . sanitize_text_field( wp_unslash( $_SERVER['HTTP_REFERER'] ) ) );
-			exit;
+			if ( isset( $_SERVER['HTTP_REFERER'] ) ) {
```
Comment (handelce) [inline product-input-fields-for-woocommerce.php:247]: @PratapDungrani We should handle a case where `$_SERVER['HTTP_REFERER']` is not set.

File: product-input-fields-for-woocommerce.php [hunk 3]
```diff
@@ -258,9 +258,9 @@ public static function init_tracker_completed() {
 		public static function pif_ts_tracker_display_notice( $is_flag ) {
 			global $current_section;
 
-			if ( isset( $_GET['page'] ) && ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['page'] ) ) ) && 'wc-settings' === $_GET['page'] ) {
+			if ( isset( $_GET['page'] ) && 'wc-settings' === $_GET['page'] ) { // phpcs:ignore
```
Comment (handelce) [inline product-input-fields-for-woocommerce.php:261]: @PratapDungrani How about getting the PHPCS fixed instead of ignoring them?

**Review by handelce — CHANGES_REQUESTED** [review]

File: includes/component/plugin-tracking/class-tyche-plugin-tracking.php (hunk 1 above)
Comment (handelce) [reply includes/component/plugin-tracking/class-tyche-plugin-tracking.php:246]: @PratapDungrani You also need to update this code change on the Plugin Tracking repo.

File: includes/component/plugin-tracking/class-tyche-plugin-tracking.php [hunk 4]
```diff
@@ -239,12 +239,8 @@ public function display_tracker_html_template() {
 
 			$current_screen = get_current_screen();
 
-			if ( 'page' === get_post_type() || 'post' === get_post_type() || ( method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor() ) || ( function_exists( 'is_gutenberg_page' ) && is_gutenberg_page() ) ) {
-				return;
-			}
-
 			$is_specific_page = apply_filters( $this->plugin_short_name . '_ts_tracker_display_notice', true );
-			if ( ! $is_specific_page ) {
+			if ( ! $is_specific_page || 'page' === get_post_type() || 'post' === get_post_type() || ( method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor() ) || ( function_exists( 'is_gutenberg_page' ) && is_gutenberg_page() ) ) {
```
Comment (handelce) [inline includes/component/plugin-tracking/class-tyche-plugin-tracking.php:243]: @PratapDungrani How about this?

```
if ( 'page' === get_post_type() || 'post' === get_post_type() || ( method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor() ) || ( function_exists( 'is_gutenberg_page' ) && is_gutenberg_page() ) || ! apply_filters( $this->plugin_short_name . '_ts_tracker_display_notice', true ) ) {
				return;
			}
```

File: product-input-fields-for-woocommerce.php [hunk 5]
```diff
@@ -244,10 +244,9 @@ public static function ts_admin_notices_scripts() {
 		 * Add tracker completed.
 		 */
 		public static function init_tracker_completed() {
-			if ( isset( $_SERVER['HTTP_REFERER'] ) ) {
-				header( 'Location: ' . sanitize_text_field( wp_unslash( $_SERVER['HTTP_REFERER'] ) ) );
-				exit;
-			}
+			$redirect_url = isset( $_SERVER['HTTP_REFERER'] ) ? sanitize_text_field( wp_unslash( $_SERVER['HTTP_REFERER'] ) ) : admin_url( 'admin.php?page=wc-settings&tab=alg_wc_pif' );
```
Comment (handelce) [inline product-input-fields-for-woocommerce.php:247]: @PratapDungrani I think it should be `sanitize_url` and not `sanitize_text_field` since we're dealing with a URL in this case.

**Review by handelce — CHANGES_REQUESTED** [review]

File: product-input-fields-for-woocommerce.php [hunk 6]
```diff
@@ -55,6 +55,18 @@ function get_wc_pif_option( $option, $default = false ) {
 	}
 }
 
+require_once 'includes/component/plugin-tracking/class-tyche-plugin-tracking.php';
```
Comment (handelce) [inline product-input-fields-for-woocommerce.php:58]: @PratapDungrani I mentioned that this should be outside of the `is_admin()` code block and not outside of the plugin class altogether. Please add it back to the `includes()` function, probably at the start of the function [here](https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/blob/ff6bb0673e4768436e28086e9dcb9c7be3a68b90/product-input-fields-for-woocommerce.php#L151)

**Review by handelce — CHANGES_REQUESTED** [review]

File: product-input-fields-for-woocommerce.php (hunk 6 above)
Comment (PratapDungrani) [reply product-input-fields-for-woocommerce.php:58]: I tried that first but it still did not work and hence I placed it outside class.

Comment (PratapDungrani) [reply product-input-fields-for-woocommerce.php]: I have added the code where you have suggested and it worked for me as well. Thanks

**Review by handelce — APPROVED** [review]
